[theme]
name = "Material Dark Orange"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

[theme.base]
white = "#eeffff"
black = "#212121"
grey = "#616161"
blue = "#82aaff"
red = "#f07178"
yellow = "#ffcb6b"
orange = "#f78c6c"
green = "#c3e88d"
purple = "#c792ea"
cyan = "#89ddff"
magenta = "#C678DD"

[theme.syntax]
"comment" = "$grey"
"constant" = "$yellow"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$orange"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"
"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"
"keyword" = "$orange"
"selfKeyword" = "$yellow"
"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"
"variable.other.member" = "$red"
"string" = "$green"
"type.builtin" = "$cyan"
"builtinType" = "$yellow"
"escape" = "$cyan"
"embedded" = "$cyan"

[theme.ui]
"lapce.active_tab" = "$black"
"lapce.inactive_tab" = "$grey"
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "$black"
"lapce.border" = "$black"
"lapce.scroll_bar" = "#FF9800"

"editor.background" = "$black"
"editor.foreground" = "$white"
"editor.dim" = "$grey"
"editor.focus" = "$white"
"editor.caret" = "#FF9800"
"editor.selection" = "$grey"
"editor.current_line" = "#1A1A1A"
"editor.link" = "$cyan"

# Git
"source_control.added" = "$green"
"source_control.removed" = "$red"
"source_control.modified" = "$blue"

"inlay_hint.foreground" = "$cyan"
"inlay_hint.background" = "$black"

# Modal
"palette.background" = "$black"
"palette.current" = "#1A1A1A"

"completion.background" = "#1A1A1A"
"completion.current" = "$grey"

"hover.background" = "$grey"

"activity.background" = "$black"
"activity.current" = "#1A1A1A"

"panel.background" = "#1A1A1A"
"panel.current" = "#grey"
"panel.hovered" = "$grey"

"status.background" = "#1A1A1A"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "$yellow"
"status.modal.terminal" = "$purple"

"markdown.blockquote" = "$orange"

"terminal.cursor" = "$white"
"terminal.foreground" = "$white"
"terminal.background" = "#1A1A1A"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "$white"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "$black"
